name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. مهم‌ترین بخش (Fix اصلی)
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. تولید فایل snake
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: majid-derhambakhsh
          outputs: dist/github-contribution-grid-snake.svg

      # 3. deploy به branch جدا
      - name: Deploy to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
